[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mqtt"]

# 1) API: redirige /api/* a functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2) SPA fallback (colócalo después del redirect de /api)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
